### ISSUE TITLE
Ability to Comment within Query

### ISSUE THREAD

**Issue by alexwalling** [iddogino/rapidql#16]
EX/ 
```Javascript
let query = 
`{ 
    - RapidAPI.YahooWeatherAPI.getWeatherForecast(
        location: city
    ) {
        - query{ 
            - results {
                - channel {
                    - item {
                        forecast {
                            high,
                            low,
                           // text
                        }
                    }
                }
            }
        }
    }
}`;
```

**Comment by iddogino** [comment]
@alexwalling any thoughts about commenting style? A few of the top of my head:

// I'm a C-style comment
-- I'm an SQL / Lua comment
# I'm a python comment

**Comment by iddogino** [comment]
**From a design perspective:** 

Currently the parser wrapper just removes white spaces, so the language grammer doent have a sense for "lines" (https://github.com/iddogino/rapidql/blob/master/src/Parser/Parser.js#L15).

One way to possible go about it is to have a step before white-space removal called "removeComments". It'll itterate all the lines in the query, and for each file, if the first charechter match a predefined charechter (comment delimiter), the line will get removed.
