### ISSUE TITLE
If passing parameter with spaces to a function, spaces get removed

### ISSUE THREAD

**Issue by iddogino** [iddogino/rapidql#6]
For instance, this:

```
Redis.local.hmset(key:"iddo", value:{city:"san francisco"}) {
        name,
        email
    }
```

Will change the value to `sanfrancisco` with no space.

**Comment by Spyes** [comment]
This is something that I'm working on actually as it affects issues 4 and 5

**Comment by iddogino** [comment]
We have commits in place for both #4 and #5.
Happy to compare notes.

**Comment by Spyes** [comment]
@iddogino awesome, sadly haven't had much time to look into them further, so I'll check out your commits

**Comment by Spyes** [comment]
@iddogino checkout PR https://github.com/iddogino/rapidql/pull/8
